/**
 * build-sitemap — writes public/sitemap.xml from src/data/seo.js.
 * ---------------------------------------------------------------------------
 *   node scripts/build-sitemap.mjs
 *   npm run sitemap
 *
 * It also runs automatically at the start of every `npm run build` (see the
 * plugin in vite.config.js), so the file in the repo can never fall behind the
 * routes the app actually serves. Add a service category with its SEO copy in
 * seo.js and it appears here on the next build.
 *
 * It lands in public/ rather than being emitted straight into dist/ so the
 * file is a real, readable, committable thing — Vite copies public/ into the
 * build for free, and the dev server serves it at /sitemap.xml with no extra
 * middleware. server.js reads it back to decide which URLs deserve a 200.
 *
 * Changing domain? Edit SITE.url in src/data/seo.js and the Sitemap: line in
 * public/robots.txt, then re-run this.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { SITEMAP, absolute } from '../src/data/seo.js'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT = path.join(ROOT, 'public', 'sitemap.xml')

export function buildSitemap() {
  const lastmod = new Date().toISOString().slice(0, 10)
  const urls = SITEMAP.map(({ path: p, changefreq, priority }) => [
    '  <url>',
    `    <loc>${absolute(p)}</loc>`,
    `    <lastmod>${lastmod}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n')).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/build-sitemap.mjs from src/data/seo.js.
     Do not hand-edit: the next build overwrites it. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`
}

/** Writes the file only when the URL list changed, so a rebuild that adds
 *  nothing doesn't show up as a diff purely because the date moved on. */
export function writeSitemap({ quiet = false } = {}) {
  const next = buildSitemap()
  const previous = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''
  const strip = (s) => s.replace(/<lastmod>[^<]*<\/lastmod>/g, '')

  if (previous && strip(previous) === strip(next)) {
    if (!quiet) console.log(`sitemap.xml unchanged (${SITEMAP.length} URLs)`)
    return false
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true })
  fs.writeFileSync(OUT, next, 'utf8')
  if (!quiet) console.log(`wrote public/sitemap.xml — ${SITEMAP.length} URLs`)
  return true
}

// Only act when run directly, so importing it from vite.config.js is free.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeSitemap()
}
