/**
 * build-logos — derives the web logo set from the supplied brand artwork.
 * ---------------------------------------------------------------------------
 *   node scripts/build-logos.mjs
 *   npm run logos
 *
 * Source of truth: "Logo Design/Logo White/Logo Design White.svg" — the
 * transparent full-colour master. (The folder name means "for white
 * backgrounds"; the artwork itself is the blue-and-green logo.)
 *
 * WHY THIS EXISTS. The master is a 1300x800 canvas with the artwork floating
 * somewhere inside it, so any <img width/height> taken from it is wrong and
 * the logo can't be positioned predictably in CSS. Everything written here is
 * cropped to the real ink, which makes the stated aspect ratio true.
 *
 * Outputs:
 *   public/favicon.svg           square, padded  — tab icon / manifest
 *   src/assets/logo/logo-mark.svg   377 x 422    — header brand mark
 *   src/assets/logo/logo-full.svg   678 x 641    — light backgrounds
 *   src/assets/logo/logo-white.svg  678 x 641    — dark backgrounds (knockout)
 *   src/lib/logoMark.js                          — emblem as data, for the
 *                                                  per-section tinted favicon
 *
 * Re-run it if the brand artwork ever changes. The path indices below assume
 * the master's 25 paths in their current order — if the designer re-exports
 * with a different structure, check the crop boxes before trusting the output.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SRC = path.join(ROOT, 'Logo Design', 'Logo White', 'Logo Design White.svg')

const GREEN = '#88bd40'
const BLUE = '#084e8d'

/**
 * Path indices making up the emblem (Burj skyline, green ring, wave, two
 * sparkles). Everything else is the "Dubai FineCLEAN" wordmark below it.
 */
const EMBLEM_IDX = new Set([0, 1, 2, 13, 14, 21, 22, 23, 24])

// Crop boxes, measured from the path data:
//   emblem   x 482.3-848.4  y  86.5-498.1
//   lockup   x 317.2-983.1  y  86.5-714.6
const MARK_BOX = { viewBox: '477 81 377 422', width: 377, height: 422 }
const LOCKUP_BOX = { viewBox: '311 80 678 641', width: 678, height: 641 }
// The favicon box is square and generously padded so the ring never touches
// the edge of a 16px tab icon.
const FAVICON_BOX = { viewBox: '445 72 440 440', width: 440, height: 440 }

if (!fs.existsSync(SRC)) {
  console.error(`Brand artwork not found:\n  ${SRC}\nNothing written.`)
  process.exit(1)
}

const src = fs.readFileSync(SRC, 'utf8')
const paths = [...src.matchAll(/<path\s+class="(cls-[12])"\s+d="([^"]*)"\s*\/>/g)]
  .map((m) => ({ green: m[1] === 'cls-1', d: m[2] }))

if (paths.length !== 25) {
  console.error(`Expected 25 paths in the master, found ${paths.length}.`)
  console.error('The artwork has been re-exported — re-check EMBLEM_IDX and the crop boxes.')
  process.exit(1)
}

const emblem = paths.filter((_, i) => EMBLEM_IDX.has(i))

const render = ({ viewBox, width, height, list, mono, title, desc }) => `\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="${width}" height="${height}" role="img" aria-label="${title}">
  <title>${title}</title>
  <desc>${desc}</desc>
${list.map((p) => `  <path fill="${mono || (p.green ? GREEN : BLUE)}" d="${p.d}"/>`).join('\n')}
</svg>
`

const write = (rel, contents) => {
  const file = path.join(ROOT, rel)
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, contents, 'utf8')
  console.log(`  ${rel.padEnd(38)} ${(contents.length / 1024).toFixed(1)} KB`)
}

const MARK_DESC = 'Dubai skyline mark in a green ring above a wave.'

console.log('Deriving the web logo set from the brand artwork:\n')

write('public/favicon.svg', render({
  ...FAVICON_BOX, list: emblem, title: 'Dubai Fine Clean', desc: MARK_DESC,
}))

write('src/assets/logo/logo-mark.svg', render({
  ...MARK_BOX, list: emblem, title: 'Dubai Fine Clean', desc: MARK_DESC,
}))

write('src/assets/logo/logo-full.svg', render({
  ...LOCKUP_BOX, list: paths, title: 'Dubai Fine Clean',
  desc: 'Dubai Fine Clean logo in full colour, for light backgrounds.',
}))

write('src/assets/logo/logo-white.svg', render({
  ...LOCKUP_BOX, list: paths, mono: '#ffffff', title: 'Dubai Fine Clean',
  desc: 'Dubai Fine Clean logo knocked out in white, for dark backgrounds.',
}))

write('src/lib/logoMark.js', `/**
 * logoMark — the emblem from the brand artwork, as data.
 * ---------------------------------------------------------------------------
 * GENERATED by scripts/build-logos.mjs. Do not hand edit — re-run \`npm run
 * logos\` if the artwork in "Logo Design/" changes.
 *
 * It lives as data (rather than as a file in public/) because the favicon is
 * re-tinted per section at runtime: see lib/favicon.js.
 */

/** Square viewBox with padding, so the ring never touches the icon edge. */
export const MARK_VIEWBOX = '${FAVICON_BOX.viewBox}'

/** The two brand colours, exactly as the artwork defines them. */
export const BRAND_GREEN = '${GREEN}'
export const BRAND_BLUE = '${BLUE}'

/**
 * Emblem paths in paint order. \`green: true\` marks the ring, the lower wave
 * and the small sparkle — the parts that take the section accent colour.
 */
export const MARK_PATHS = [
${emblem.map((p) => `  { green: ${p.green}, d: '${p.d}' },`).join('\n')}
]
`)

console.log('\nDone.')
